---
kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: inject-chaos-into-server-pod
  namespace: asr-engine
spec:
  selector:
    namespaces:
      - asr-engine
    labelSelectors:
      "server.service": "decoding-sdk-server"
  mode: one
  action: pod-failure
  duration: 120s
  gracePeriod: 0
--- 
kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: inject-chaos-into-server-pod
  namespace: asr-engine
spec:
  selector:
    namespaces:
      - asr-engine
    labelSelectors:
      worker.service: decoding-sdk-worker
  mode: all
  action: pod-kill
  duration: 60s
  gracePeriod: 0
