--- 
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: inject-mem-stress-into-worker-pod
  namespace: asr-engine
spec:
  mode: one
  selector:
    namespaces:
      - asr-engine
    labelSelectors:
      worker.service: decoding-sdk-worker
  stressors:
    memory:
      workers: 4
      size: '256MB'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: inject-mem-stress-into-server-pod
  namespace: asr-engine
spec:
  mode: one
  selector:
    namespaces:
      - asr-engine
    labelSelectors:
      "server.service": "decoding-sdk-server"
  stressors:
    memory:
      workers: 4
      size: '256MB'